{
    "id" : <?php echo $this->bigleader["player_id"]; ?>,
    "name" : "<?php echo $this->bigleader["player_name"]; ?>",
    "channel" : "<?php echo $this->bigleader["channel"]; ?>",
    "overallRank" : <?php echo 0; ?>,
    "overallRating" : <?php echo 0; ?>,
    "totalRaces" : <?php echo $this->bigleader["numRaces"]; ?>,
    "totalGames" : <?php echo $this->bigleader["numGames"]; ?>,
    "totalTimePlayed" : <?php echo $this->bigleader["timePlayed"]; ?>,
    "totalFirstPlace" : <?php echo $this->bigleader["numWins"]; ?>,
    "totalSecondPlace" : <?php echo 0; ?>,
    "totalThirdPlace" : <?php echo 0; ?>,
    "totalQuits" : <?php echo 0; ?>,
    "totalDisqualifications" : <?php echo 0; ?>
}