{
    "totalRaces" : <?php echo $this->stat["totalRaces"]; ?>,
    "totalPlayers" : <?php echo $this->stat["totalPlayers"]; ?>,
    "totalGames" : <?php echo $this->stat["totalGames"]; ?>,
    "largestRace" : <?php echo $this->stat["largestRaceId"]; ?>,
    "largestRaceSize" : <?php echo $this->stat["largestRaceSize"]; ?>,
    "totalRaceTime" : <?php echo $this->stat["totalRaceTime"]; ?>,
    "totalTimePlayed" : <?php echo $this->stat["totalPlayedTime"]; ?>
}