{
    "rank" : <?php echo 0; ?>,
    "totalRaces" : <?php echo $this->stat["totalRaces"]; ?>,
    "totalGames" : <?php echo $this->stat["totalGames"]; ?>,
    "firstRace" : <?php echo $this->stat["firstRaceId"]; ?>,
    "firstRaceDate" : <?php echo $this->stat["firstRaceDate"]; ?>,
    "totalTimePlayed" : <?php echo $this->stat["totalPlayedTime"]; ?>,
    "totalFirstPlace" : <?php echo $this->stat["totalFirsts"]; ?>,
    "totalSecondPlace" : <?php echo $this->stat["totalSeconds"]; ?>,
    "totalThirdPlace" : <?php echo $this->stat["totalThirds"]; ?>,
    "totalQuits" : <?php echo $this->stat["totalQuits"]; ?>,
    "totalDisqualifications" : <?php echo $this->stat["totalDQs"]; ?>
}