[
{
"name": "ou_j",
"totalRaces": "3796",
"totalGames": "3",
"totalTimePlayed": "2814423",
"totalFirstPlace": "1273"
},
{
"name": "neskamikaze",
"totalRaces": "2760",
"totalGames": "769",
"totalTimePlayed": "5217276",
"totalFirstPlace": "1229"
},
{
"name": "Barnowl",
"totalRaces": "2714",
"totalGames": "48",
"totalTimePlayed": "4730093",
"totalFirstPlace": "1074"
},
{
"name": "Hyphenated",
"totalRaces": "2402",
"totalGames": "41",
"totalTimePlayed": "2423144",
"totalFirstPlace": "1253"
},
{
"name": "ceehe",
"totalRaces": "2150",
"totalGames": "1",
"totalTimePlayed": "987686",
"totalFirstPlace": "450"
},
{
"name": "_910dan",
"totalRaces": "2096",
"totalGames": "8",
"totalTimePlayed": "2257761",
"totalFirstPlace": "770"
},
{
"name": "luke994",
"totalRaces": "2069",
"totalGames": "17",
"totalTimePlayed": "5092775",
"totalFirstPlace": "1322"
},
{
"name": "Midboss",
"totalRaces": "1677",
"totalGames": "699",
"totalTimePlayed": "6589106",
"totalFirstPlace": "593"
},
{
"name": "Zamiel",
"totalRaces": "1648",
"totalGames": "5",
"totalTimePlayed": "1132808",
"totalFirstPlace": "740"
},
{
"name": "extraguy",
"totalRaces": "1614",
"totalGames": "65",
"totalTimePlayed": "1410394",
"totalFirstPlace": "635"
},
{
"name": "Garrison",
"totalRaces": "1508",
"totalGames": "98",
"totalTimePlayed": "2873441",
"totalFirstPlace": "409"
},
{
"name": "antizoubilamaka",
"totalRaces": "1438",
"totalGames": "7",
"totalTimePlayed": "1490959",
"totalFirstPlace": "842"
},
{
"name": "bboyvenom",
"totalRaces": "1376",
"totalGames": "52",
"totalTimePlayed": "1301193",
"totalFirstPlace": "423"
},
{
"name": "Exodus",
"totalRaces": "1366",
"totalGames": "21",
"totalTimePlayed": "5749784",
"totalFirstPlace": "545"
},
{
"name": "Dea1h",
"totalRaces": "1357",
"totalGames": "2",
"totalTimePlayed": "879699",
"totalFirstPlace": "639"
},
{
"name": "sicko",
"totalRaces": "1345",
"totalGames": "53",
"totalTimePlayed": "3143109",
"totalFirstPlace": "631"
},
{
"name": "Elminster",
"totalRaces": "1306",
"totalGames": "27",
"totalTimePlayed": "4833114",
"totalFirstPlace": "287"
},
{
"name": "Blechy",
"totalRaces": "1286",
"totalGames": "630",
"totalTimePlayed": "3368715",
"totalFirstPlace": "554"
},
{
"name": "alaris_villain",
"totalRaces": "1268",
"totalGames": "16",
"totalTimePlayed": "4209595",
"totalFirstPlace": "266"
},
{
"name": "jkoper",
"totalRaces": "1237",
"totalGames": "19",
"totalTimePlayed": "6222317",
"totalFirstPlace": "281"
},
{
"name": "Cyber_1",
"totalRaces": "1221",
"totalGames": "2",
"totalTimePlayed": "832738",
"totalFirstPlace": "553"
},
{
"name": "Acmlm",
"totalRaces": "1217",
"totalGames": "123",
"totalTimePlayed": "5148666",
"totalFirstPlace": "391"
},
{
"name": "chum",
"totalRaces": "1212",
"totalGames": "219",
"totalTimePlayed": "1815763",
"totalFirstPlace": "546"
},
{
"name": "Xelnas",
"totalRaces": "1180",
"totalGames": "20",
"totalTimePlayed": "597657",
"totalFirstPlace": "149"
},
{
"name": "Gregortixlkyns",
"totalRaces": "1179",
"totalGames": "7",
"totalTimePlayed": "5577648",
"totalFirstPlace": "821"
},
{
"name": "thisguyisbarry",
"totalRaces": "1176",
"totalGames": "2",
"totalTimePlayed": "615730",
"totalFirstPlace": "422"
},
{
"name": "mrbubbleskp",
"totalRaces": "1151",
"totalGames": "19",
"totalTimePlayed": "6494121",
"totalFirstPlace": "223"
},
{
"name": "Kosmicd12",
"totalRaces": "1128",
"totalGames": "47",
"totalTimePlayed": "3041455",
"totalFirstPlace": "475"
},
{
"name": "theJUICE",
"totalRaces": "1125",
"totalGames": "84",
"totalTimePlayed": "2764101",
"totalFirstPlace": "328"
},
{
"name": "thalen22",
"totalRaces": "1113",
"totalGames": "3",
"totalTimePlayed": "797213",
"totalFirstPlace": "307"
},
{
"name": "duneaught",
"totalRaces": "1111",
"totalGames": "21",
"totalTimePlayed": "1342316",
"totalFirstPlace": "350"
},
{
"name": "Narcissa",
"totalRaces": "1084",
"totalGames": "42",
"totalTimePlayed": "3969240",
"totalFirstPlace": "625"
},
{
"name": "guhungamanga",
"totalRaces": "1077",
"totalGames": "24",
"totalTimePlayed": "2057675",
"totalFirstPlace": "446"
},
{
"name": "SNIPING117",
"totalRaces": "1063",
"totalGames": "13",
"totalTimePlayed": "4508367",
"totalFirstPlace": "369"
},
{
"name": "Eunos",
"totalRaces": "1063",
"totalGames": "12",
"totalTimePlayed": "4782345",
"totalFirstPlace": "390"
},
{
"name": "speedruntrainer",
"totalRaces": "1043",
"totalGames": "36",
"totalTimePlayed": "2160345",
"totalFirstPlace": "375"
},
{
"name": "KableKiB",
"totalRaces": "1043",
"totalGames": "25",
"totalTimePlayed": "1414265",
"totalFirstPlace": "600"
},
{
"name": "kzez",
"totalRaces": "1042",
"totalGames": "146",
"totalTimePlayed": "2910849",
"totalFirstPlace": "259"
},
{
"name": "imwaytopunny",
"totalRaces": "1028",
"totalGames": "6",
"totalTimePlayed": "994196",
"totalFirstPlace": "348"
},
{
"name": "Andy",
"totalRaces": "978",
"totalGames": "124",
"totalTimePlayed": "3098169",
"totalFirstPlace": "418"
},
{
"name": "nudua",
"totalRaces": "978",
"totalGames": "160",
"totalTimePlayed": "1740950",
"totalFirstPlace": "470"
},
{
"name": "Jiano",
"totalRaces": "963",
"totalGames": "43",
"totalTimePlayed": "3317893",
"totalFirstPlace": "398"
},
{
"name": "SamuelioX",
"totalRaces": "963",
"totalGames": "16",
"totalTimePlayed": "1292957",
"totalFirstPlace": "334"
},
{
"name": "ZGSpeedruns",
"totalRaces": "960",
"totalGames": "13",
"totalTimePlayed": "1609049",
"totalFirstPlace": "527"
},
{
"name": "OhMyGoth",
"totalRaces": "952",
"totalGames": "2",
"totalTimePlayed": "582595",
"totalFirstPlace": "253"
},
{
"name": "HauntedQuest",
"totalRaces": "942",
"totalGames": "3",
"totalTimePlayed": "719181",
"totalFirstPlace": "383"
},
{
"name": "Pokey",
"totalRaces": "923",
"totalGames": "37",
"totalTimePlayed": "1945153",
"totalFirstPlace": "433"
},
{
"name": "flanthis",
"totalRaces": "898",
"totalGames": "24",
"totalTimePlayed": "4067926",
"totalFirstPlace": "268"
},
{
"name": "Xelna",
"totalRaces": "897",
"totalGames": "18",
"totalTimePlayed": "4658035",
"totalFirstPlace": "762"
},
{
"name": "MrCab",
"totalRaces": "895",
"totalGames": "78",
"totalTimePlayed": "2661479",
"totalFirstPlace": "133"
},
{
"name": "Yoshipro101",
"totalRaces": "875",
"totalGames": "166",
"totalTimePlayed": "2155584",
"totalFirstPlace": "289"
},
{
"name": "halfbaked",
"totalRaces": "875",
"totalGames": "10",
"totalTimePlayed": "972717",
"totalFirstPlace": "290"
},
{
"name": "random64",
"totalRaces": "864",
"totalGames": "52",
"totalTimePlayed": "579628",
"totalFirstPlace": "69"
},
{
"name": "kk_slida",
"totalRaces": "862",
"totalGames": "54",
"totalTimePlayed": "1147605",
"totalFirstPlace": "436"
},
{
"name": "SSBMstuff",
"totalRaces": "853",
"totalGames": "24",
"totalTimePlayed": "4133617",
"totalFirstPlace": "311"
},
{
"name": "coolkid",
"totalRaces": "834",
"totalGames": "171",
"totalTimePlayed": "1641525",
"totalFirstPlace": "455"
},
{
"name": "Kirua",
"totalRaces": "834",
"totalGames": "138",
"totalTimePlayed": "1789180",
"totalFirstPlace": "411"
},
{
"name": "ProblemsIRL",
"totalRaces": "829",
"totalGames": "4",
"totalTimePlayed": "732301",
"totalFirstPlace": "356"
},
{
"name": "TheMexicanRunner",
"totalRaces": "820",
"totalGames": "100",
"totalTimePlayed": "1713906",
"totalFirstPlace": "286"
},
{
"name": "NuRelic",
"totalRaces": "819",
"totalGames": "2",
"totalTimePlayed": "484003",
"totalFirstPlace": "167"
},
{
"name": "bangerra",
"totalRaces": "797",
"totalGames": "390",
"totalTimePlayed": "1634268",
"totalFirstPlace": "394"
},
{
"name": "simpleflips",
"totalRaces": "795",
"totalGames": "34",
"totalTimePlayed": "2535960",
"totalFirstPlace": "466"
},
{
"name": "NORG",
"totalRaces": "793",
"totalGames": "51",
"totalTimePlayed": "1118479",
"totalFirstPlace": "213"
},
{
"name": "esi",
"totalRaces": "787",
"totalGames": "32",
"totalTimePlayed": "1601877",
"totalFirstPlace": "412"
},
{
"name": "nightmare47",
"totalRaces": "778",
"totalGames": "290",
"totalTimePlayed": "3748003",
"totalFirstPlace": "204"
},
{
"name": "rat3485",
"totalRaces": "769",
"totalGames": "2",
"totalTimePlayed": "617182",
"totalFirstPlace": "243"
},
{
"name": "ilikebeingsmart",
"totalRaces": "763",
"totalGames": "11",
"totalTimePlayed": "2211222",
"totalFirstPlace": "102"
},
{
"name": "giuocob",
"totalRaces": "761",
"totalGames": "10",
"totalTimePlayed": "2355162",
"totalFirstPlace": "246"
},
{
"name": "infinitemystery",
"totalRaces": "754",
"totalGames": "122",
"totalTimePlayed": "3553930",
"totalFirstPlace": "96"
},
{
"name": "Dublin",
"totalRaces": "754",
"totalGames": "11",
"totalTimePlayed": "1788878",
"totalFirstPlace": "241"
},
{
"name": "mountebank",
"totalRaces": "753",
"totalGames": "19",
"totalTimePlayed": "4444140",
"totalFirstPlace": "444"
},
{
"name": "roopert83",
"totalRaces": "751",
"totalGames": "18",
"totalTimePlayed": "1674874",
"totalFirstPlace": "239"
},
{
"name": "dethwing",
"totalRaces": "751",
"totalGames": "48",
"totalTimePlayed": "1954098",
"totalFirstPlace": "246"
},
{
"name": "DKlaww",
"totalRaces": "750",
"totalGames": "2",
"totalTimePlayed": "419579",
"totalFirstPlace": "96"
},
{
"name": "MSDS3170",
"totalRaces": "750",
"totalGames": "43",
"totalTimePlayed": "1730810",
"totalFirstPlace": "225"
},
{
"name": "JoeDamillio",
"totalRaces": "744",
"totalGames": "16",
"totalTimePlayed": "2955271",
"totalFirstPlace": "234"
},
{
"name": "ivan",
"totalRaces": "743",
"totalGames": "126",
"totalTimePlayed": "3174207",
"totalFirstPlace": "238"
},
{
"name": "Sluip",
"totalRaces": "743",
"totalGames": "32",
"totalTimePlayed": "1419067",
"totalFirstPlace": "306"
},
{
"name": "peppicx",
"totalRaces": "742",
"totalGames": "3",
"totalTimePlayed": "385049",
"totalFirstPlace": "132"
},
{
"name": "bony",
"totalRaces": "738",
"totalGames": "385",
"totalTimePlayed": "1987023",
"totalFirstPlace": "162"
},
{
"name": "deejumbles",
"totalRaces": "733",
"totalGames": "3",
"totalTimePlayed": "393290",
"totalFirstPlace": "100"
},
{
"name": "Darko",
"totalRaces": "731",
"totalGames": "83",
"totalTimePlayed": "2538985",
"totalFirstPlace": "264"
},
{
"name": "HiQConsoul",
"totalRaces": "729",
"totalGames": "2",
"totalTimePlayed": "593341",
"totalFirstPlace": "151"
},
{
"name": "rageagainstfaces",
"totalRaces": "726",
"totalGames": "62",
"totalTimePlayed": "605152",
"totalFirstPlace": "33"
},
{
"name": "qwerty1605",
"totalRaces": "725",
"totalGames": "15",
"totalTimePlayed": "1825922",
"totalFirstPlace": "73"
},
{
"name": "darkdragonx6",
"totalRaces": "724",
"totalGames": "15",
"totalTimePlayed": "648716",
"totalFirstPlace": "174"
},
{
"name": "Siglemic",
"totalRaces": "724",
"totalGames": "18",
"totalTimePlayed": "2573302",
"totalFirstPlace": "280"
},
{
"name": "metanightmare22",
"totalRaces": "722",
"totalGames": "82",
"totalTimePlayed": "996875",
"totalFirstPlace": "132"
},
{
"name": "SOMETHING915",
"totalRaces": "715",
"totalGames": "38",
"totalTimePlayed": "1486890",
"totalFirstPlace": "162"
},
{
"name": "ParadoxKarl",
"totalRaces": "712",
"totalGames": "36",
"totalTimePlayed": "1499142",
"totalFirstPlace": "248"
},
{
"name": "dram55",
"totalRaces": "710",
"totalGames": "29",
"totalTimePlayed": "1118852",
"totalFirstPlace": "448"
},
{
"name": "doicm",
"totalRaces": "695",
"totalGames": "99",
"totalTimePlayed": "1963860",
"totalFirstPlace": "232"
},
{
"name": "Wawlconut",
"totalRaces": "678",
"totalGames": "178",
"totalTimePlayed": "1578863",
"totalFirstPlace": "160"
},
{
"name": "Gombill",
"totalRaces": "677",
"totalGames": "14",
"totalTimePlayed": "2861519",
"totalFirstPlace": "253"
},
{
"name": "PrinceKaro",
"totalRaces": "674",
"totalGames": "232",
"totalTimePlayed": "2009308",
"totalFirstPlace": "139"
},
{
"name": "keeta",
"totalRaces": "670",
"totalGames": "47",
"totalTimePlayed": "2120797",
"totalFirstPlace": "290"
},
{
"name": "mugg",
"totalRaces": "665",
"totalGames": "30",
"totalTimePlayed": "925908",
"totalFirstPlace": "216"
},
{
"name": "atozmos",
"totalRaces": "665",
"totalGames": "3",
"totalTimePlayed": "604403",
"totalFirstPlace": "174"
},
{
"name": "altidorian",
"totalRaces": "653",
"totalGames": "4",
"totalTimePlayed": "825419",
"totalFirstPlace": "240"
},
{
"name": "Jimmie1717",
"totalRaces": "649",
"totalGames": "17",
"totalTimePlayed": "3470619",
"totalFirstPlace": "410"
}
]
